name: applify-stack

include:
  - Backend/docker-compose.yml

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://api-gateway:80
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/index.html:/app/index.html
      - ./Frontend/vite.config.js:/app/vite.config.js
      - ./Frontend/public:/app/public
    depends_on:
      - api-gateway
