version: "1"
services:
  # ----------------------------------------------------
  # MONOLITHIC BACKEND (All Microservices + Nginx Gateway)
  # ----------------------------------------------------
  - type: web
    name: applify-backend
    env: docker
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    plan: free # Change this to starter/standard if needed
    envVars:
      - key: PORT
        value: 80
